INSERT INTO public.teaching_logs (user_id,semester,week,date_from,date_to,subject_name,subject_code,topic,attendance,methods,content_methods,media,apps,evaluation,outcome_cognitive,outcome_psychomotor,outcome_affective,outcome_application,problem,solution,created_at,updated_at,head_curriculum,deputy_academic,director,teaching_date) VALUES
	 (2,'1/2569',1,'2026-07-15','2026-07-15','กิจกรรมในสถานประกอบการ','21901-2222','กิจกรรมเสริมสร้างสุจริตจิตอาสา','[{"date": "2026-07-15", "week": 1, "total": 27, "period": "8-9", "date_to": "", "present": 24, "percentage": 88.9, "time_range": "15.00-17.00"}]','{"format_onair": false, "format_other": false, "other_detail": "", "format_onhand": false, "format_online": true, "format_onsite": false, "format_ondemand": true}','{"game": false, "pjbl": false, "stem": false, "other": false, "center": false, "lecture": true, "situation": false, "case_study": true, "discussion": true, "experiment": false, "other_detail": ""}','{"doc": true, "ppt": true, "book": true, "ebook": false, "model": false, "other": false, "worksheet": false, "other_detail": ""}','{"line": true, "zoom": true, "other": false, "facebook": false, "classroom": true, "other_detail": ""}','{}','พุทธพิสัยเริ่ด','ทักษะเริ่ด','จิตพิสัยเริ่ด','ประยุกต์เริ่ด','ไม่มีปัญหา','ไม่มีข้อเสนอแนะ','2026-07-14 10:20:51.858357+07','2026-07-14 10:20:51.858357+07','นายวิโรจน์ ยาบุษดี','ว่าที่ร้อยตรีชัชวาลย์ ป้อมสุวรรณ','นายศุภกฤต แกมนิรัตน์',NULL),
	 (2,'1/2569',8,'2026-07-13','2026-07-17','กิจกรรมในสถานประกอบการวีค 8','21901-2222','เรื่อง / หัวข้อที่สอน
','[{"date": "2026-07-15", "week": 8, "total": 27, "period": "8-9", "date_to": "", "present": 7, "percentage": 25.9, "time_range": "15.00-17.00"}]','{"format_onair": false, "format_other": false, "other_detail": "", "format_onhand": false, "format_online": false, "format_onsite": true, "format_ondemand": false}','{"game": false, "pjbl": false, "stem": false, "other": false, "center": true, "lecture": true, "situation": false, "case_study": false, "discussion": false, "experiment": false, "other_detail": ""}','{"doc": false, "ppt": true, "book": false, "ebook": false, "model": false, "other": false, "worksheet": false, "other_detail": ""}','{"line": true, "zoom": false, "other": false, "facebook": false, "classroom": true, "other_detail": ""}','{}','พุทธิพิสัย
','ทักษะพิสัย
','จิตพิสัย
','การประยุกต์
','ปัญหาในการจัดการเรียนรู้
','แนวทางการแก้ไขและพัฒนา
','2026-07-14 11:01:39.859327+07','2026-07-14 11:01:39.859327+07','นายวิโรจน์ ยาบุษดี','ว่าที่ร้อยตรีชัชวาลย์ ป้อมสุวรรณ','นายศุภกฤต แกมนิรัตน์','2026-07-14');
